version: '3.9'

services:
    backend:
        build: ./backend
        container_name: pizzaria-backend
        ports:
            - '5001:5000'
        networks:
            - pizzaria-network

    frontend:
        build: ./frontend
        container_name: pizzaria-frontend
        ports:
            - '8080:8080'
        depends_on:
            - backend
        networks:
            - pizzaria-network

networks:
    pizzaria-network:
        driver: bridge
