---
- name: Configurar servidor com Docker
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Atualizar cache do APT
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Instalar pacotes base
      apt:
        name:
          - docker.io
          - docker-compose
          - git
          - curl
          - python3-pip
        state: present
    - name: Iniciar e habilitar Docker
      systemd:
        name: docker
        state: started
        enabled: true
    - name: Adicionar usuario admin ao grupo docker
      user:
        name: admin
        groups: docker
        append: true
    - name: Verificar se Docker esta funcional
      command: docker ps
      changed_when: false
      register: docker_test
    - name: Mostrar status do Docker
      debug:
        msg: OK Docker configurado com sucesso
      when: docker_test.rc == 0
