---
name: 01-AWS-provisioning
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8
      - name: Inicializar Terraform
        run: |
          cd infra/terraform
          terraform init -input=false
      - name: Executar Terraform Apply
        run: |
          cd infra/terraform
          terraform apply -auto-approve
      - name: Disparar workflow do Ansible
        uses: peter-evans/workflow-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          workflow: ansible-deploy.yml
          ref: main